import { NextRequest, NextResponse } from 'next/server'
import { getAdminDb } from '@/lib/firebase/admin'
import { requireAdmin } from '@/lib/server/adminAuth'
import { writeAudit } from '@/lib/server/audit'
import { StockSession, opAlreadyDone, claimOp } from '@/lib/server/stock'
import { add, deduct, count } from '@/lib/inventory/engine'
import { Refused, readJson, handleRouteError, isOpId, isMilli, isIsoDate } from '@/lib/server/http'

export const runtime = 'nodejs'

const REASONS = ['restock', 'damaged', 'expired', 'count'] as const
type AdjustReason = (typeof REASONS)[number]

/**
 * One stock change on one managed product: restock (+), damaged (−),
 * expired (−), or count correction (set to the counted amount). Every
 * change is a ledger movement with who, when, why and a note. `opId` is
 * generated by the phone per tap, so a double tap applies once.
 */
export async function POST(request: NextRequest) {
  const auth = await requireAdmin(request)
  if (!auth.ok) return auth.response
  const b = await readJson(request)
  const reason = b.reason as AdjustReason
  const productId = typeof b.productId === 'string' ? b.productId : ''
  const note = typeof b.note === 'string' ? b.note.trim().slice(0, 300) : ''
  if (!isOpId(b.opId) || !productId || !REASONS.includes(reason)) {
    return NextResponse.json({ error: 'Invalid request.' }, { status: 400 })
  }
  if (reason === 'count' ? !isMilli(b.countedMilli, { allowZero: true }) : !isMilli(b.qtyMilli)) {
    return NextResponse.json({ error: 'Enter a quantity.' }, { status: 400 })
  }
  if (b.expiryDate !== undefined && b.expiryDate !== null && !isIsoDate(b.expiryDate)) {
    return NextResponse.json({ error: 'Invalid expiry date.' }, { status: 400 })
  }
  const opId = b.opId

  const db = getAdminDb()
  try {
    const result = await db.runTransaction(async (tx) => {
      if (await opAlreadyDone(tx, opId)) return { duplicate: true }
      const session = new StockSession(tx, auth.caller)
      await session.load([productId])
      const it = session.item(productId)
      if (!it.product) throw new Refused('Product not found.', 404)
      if (!it.config.managed) throw new Refused('This product is not managed here yet. Count it and switch it on first.')
      const before = { onHandMilli: it.state.onHandMilli, reservedMilli: it.state.reservedMilli }
      const meta = { opId, note }
      if (reason === 'restock') {
        const expiryDate = isIsoDate(b.expiryDate) ? b.expiryDate : null
        session.apply(productId, (s) => add(s, b.qtyMilli as number, 'restock', { batch: { id: session.newBatchId(), expiryDate, receivedAt: Date.now() } }), meta)
      } else if (reason === 'damaged' || reason === 'expired') {
        session.apply(productId, (s) => deduct(s, b.qtyMilli as number, reason === 'damaged' ? 'damaged' : 'expire'), meta)
      } else {
        session.apply(productId, (s) => count(s, b.countedMilli as number, { batch: { id: session.newBatchId(), expiryDate: null, receivedAt: Date.now() } }), meta)
      }
      claimOp(tx, opId, auth.caller, `adjust:${reason}`)
      const status = session.commit({ lastCountedAt: reason === 'count' }).get(productId) ?? null
      writeAudit(tx, auth.caller, {
        action: `stock.${reason}`,
        entityType: 'product',
        entityId: productId,
        before,
        after: { onHandMilli: it.state.onHandMilli, reservedMilli: it.state.reservedMilli },
        note,
      })
      return { duplicate: false, onHandMilli: it.state.onHandMilli, reservedMilli: it.state.reservedMilli, stockStatus: status }
    })
    return NextResponse.json({ ok: true, ...result })
  } catch (error) {
    return handleRouteError('admin/stock/adjust', error)
  }
}
